---
### group_vars/CONNECTED_ENDPOINTS.yml

# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: DC1_HOST1_VLAN100
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ G0/0, G0/1 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet8, Ethernet8 ]
        # Device names where the server ports are connected.
        switches: [ dc1-leaf1a, dc1-leaf1b ]
        # VLANs that will be configured on these ports.
        vlans: "100"
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # Description of the port channel interface.
          description: PortChannel DC1_HOST1_VLAN100
          # Port channel mode for LACP.
          mode: active

  - name: DC1_HOST2_ALL_VLANS
    adapters:
      - endpoint_ports: [ G0/0, G0/1 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ dc1-leaf2a, dc1-leaf2b ]
        vlans: 100,110,120
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel DC1_HOST2_ALL_VLANS
          mode: active
