---

# Default gateway used for the management interface
mgmt_gateway: 192.168.1.254

# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 1.1.1.0/27
    # ASN to be used by BGP
    bgp_as: 65001
  nodes:
    - name: dc1-spine1
      id: 1
      mgmt_ip: 192.168.1.1/24
    
    - name: dc1-spine2
      id: 2
      mgmt_ip: 192.168.1.2/24

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 1.1.1.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 2.2.2.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.254.0.0/27
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.254.1.0/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.254.2.0/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:10
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC1_L3_LEAF1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        # Definition of hostnames under the node_group
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 192.168.1.3/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 192.168.1.4/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2

    - group: DC1_L3_LEAF2
      bgp_as: 65102
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 192.168.1.5/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 192.168.1.6/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4

    - group: DC1_BORDER_LEAFS
      bgp_as: 65199
      evpn_gateway:
        # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: false
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: dc1-borderleaf1a
          id: 5
          mgmt_ip: 192.168.1.7/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway. If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated. Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc2-borderleaf1a
        
        - name: dc1-borderleaf1b
          id: 6
          mgmt_ip: 192.168.1.8/24
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6
          evpn_gateway:
            remote_peers:
              - hostname: dc2-borderleaf1b


