#---
#
## Custom prefix_lists and route-maps to filter the leaked routes on vrf C_DC1
#
#custom_structured_configuration_prefix_lists:
#  - name: PL_LEAK_ROUTES_C_DC2
#    sequence_numbers:
#      - sequence: 10
#        action: "permit 10.220.0.0/24"
#
#  - name: PL_LEAK_ROUTES_B_DC2
#    sequence_numbers:
#      - sequence: 10
#        action: "permit 10.210.0.0/24"
#
#  - name: PL_LEAK_ROUTES_A_DC2
#    sequence_numbers:
#      - sequence: 10
#        action: "permit 10.200.0.0/24"
#
#custom_structured_configuration_route_maps:
#  - name: RM_LEAK_ROUTES_C_DC2
#    sequence_numbers:
#      - sequence: 10
#        type: permit
#        match: 
#          - "ip address prefix_list PL_LEAK_ROUTES_C_DC2"
#
#  - name: RM_LEAK_ROUTES_B_DC2
#    sequence_numbers:
#      - sequence: 10
#        type: permit
#        match: 
#          - "ip address prefix_list PL_LEAK_ROUTES_B_DC2"
#
#  - name: RM_LEAK_ROUTES_A_DC2
#    sequence_numbers:
#      - sequence: 10
#        type: permit
#        match: 
#          - "ip address prefix_list PL_LEAK_ROUTES_A_DC2"