---
# Common AVD group variables
fabric_name: FABRIC

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Local users
local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# P2P links MTU - recommended 1500 in LAB
p2p_uplinks_mtu: 1500

# CloudVision Portal definitions
cvp_instance_ip: 192.168.1.200
terminattr_smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
terminattr_ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
terminattr_disable_aaa: true

# Define default interfaces
default_interfaces:
  - types: [ spine ]
    platforms: [ vEOS-lab ]
    uplink_interfaces: [ Ethernet1-2 ]
    downlink_interfaces: [ Ethernet1-8 ]
  - types: [ l3leaf ]
    platforms: [ vEOS-lab ]
    uplink_interfaces: [ Ethernet1-8 ]
    mlag_interfaces: [ Ethernet3-4 ]
    downlink_interfaces: [ Ethernet8, Ethernet8 ]

# L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
# Between the border leafs only for L3VNIs exchange over the VXLAN fabric
l3_edge:
  # Define a new IP pool that will be used to assign IP addresses to L3 Edge interfaces.
  p2p_links_ip_pools:
    - name: DCI_IP_pool
      ipv4_pool: 172.100.100.0/28
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    - name: DCI_profile
      ip_pool: DCI_IP_pool
      as: [65199, 65299]
      include_in_underlay_protocol: true
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
    - id: 1
      nodes: [dc1-borderleaf1a, dc2-borderleaf1a]
      interfaces: [Ethernet7, Ethernet7]
      profile: DCI_profile
    - id: 2
      nodes: [dc1-borderleaf1b, dc2-borderleaf1b]
      interfaces: [Ethernet8, Ethernet8]
      profile: DCI_profile

# Adjust default bfd values - lab only (300 and 300 by default)
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3